Watch out for properties when setting Env attributes
Mypy seems easily confused by properties, hence the "type: ignore" flag to
avoid this bogus message:

> src/e3/env.py:111: error: Too many arguments for "fset" of "property"

TN: V708-038